webscraping/project/api/urls.py
from django.urls import path

from . import views

app_name = 'project'

urlpatterns = [
    path('', views.get_scraped_items, name='api-scraped-items'),
]

webscraping/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views
from .views import SiteCreateView, SiteDeleteView, SiteDetailView, SiteListView, SiteUpdateView

urlpatterns = [
    path('', views.home, name='home'),
    path('project/<project_name>/', SiteListView.as_view(), name='site-list'),
    path('project/<project_name>/<str:pk>/', SiteDetailView.as_view(), name='site-detail'),
    path('scrape/new/', SiteCreateView.as_view(), name='new-scrape'),
    path('project/<project_name>/<str:pk>/update', SiteUpdateView.as_view(), name='update-scrape'),
    path('project/<project_name>/<site>/<str:pk>/delete', SiteDeleteView.as_view(), name='delete-scrape'),
    path('api-docs/', views.api_docs, name='api-docs'),
    path('help/', views.help, name='help'),
    path('scrape-data-json/', views.scrape_data_json, name='scrape-json'),
    path('spider-log-json/', views.spider_logs_json, name='log-json'),
    path('web-provider-json/', views.web_providers_json, name='log-json'),
    path('aim-dealer-provider-json/', views.aim_dealers_list, name='aim-dealer-json'),
    path('project/<project_name>/export_scrape_by_csv', views.scrape_data_csv, name='scrape-csv'),
    # path('api/scraped-items/', views.test_api, name='test'),
]


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webscraping/webscraping/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_view
from django.urls import include, path
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', user_views.MyLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path(
        'password-reset/',
        auth_view.PasswordResetView.as_view(
            template_name='users/password_reset.html'),
        name='password_reset'),
    path(
        'password-reset/done/',
        auth_view.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm',
    ),
    path(
        'password-reset-complete/',
        auth_view.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete',
    ),
    path('', include('project.urls')),
    # rest framework urls
    path('api/scraped-items/aim-dealers/', include('project.api.urls', 'api-scrape')),  # namespace of 'api-scrape'
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webscraping/project/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse, reverse_lazy


class Project(models.Model):
    name = models.CharField(max_length=50, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    # author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.name)


class Webprovider(models.Model):
    name = models.CharField(max_length=50, null=True)

    def __str__(self):
        return f'{self.name}' or ''


class AimDealer(models.Model):
    ACCOUNT_STATUS = (
        ('ACTIVE', 'ACTIVE'),
        ('INACTIVE', 'INACTIVE'),
        ('DELETED', 'DELETED'),
    )

    account = models.CharField(max_length=10, choices=ACCOUNT_STATUS)
    dealer_id = models.IntegerField(primary_key=True)
    dealer_name = models.CharField(max_length=200, null=True)
    site_url = models.CharField(max_length=200, null=True)
    web_provider = models.ForeignKey(
        Webprovider, on_delete=models.SET_NULL, related_name='web_provider', null=True, blank=True
    )
    account_manager = models.CharField(max_length=50, null=True, blank=True)
    note = models.TextField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    date_modified = models.DateTimeField(auto_now=True, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='author', null=True, blank=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='modified_by', null=True, blank=True)

    def __str__(self):
        return f'{self.dealer_id} - {self.dealer_name}'


class TargetSite(models.Model):
    STATUS_CHOICES = (
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
        ('Pending', 'Pending'),
        ('Failed', 'Failed'),
        ('Paused', 'Paused'),
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Pending')
    entry_code = models.CharField(max_length=20, blank=True, default='', verbose_name='entry#')
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='projects', null=True)
    site_id = models.CharField(max_length=50, primary_key=True, verbose_name='site id (domain)')  # domain_name input
    site_name = models.ForeignKey(AimDealer, on_delete=models.CASCADE, null=True)
    site_url = models.CharField(max_length=200, blank=True, null=True)
    web_provider = models.CharField(max_length=50, blank=True, null=True)
    feed_id = models.CharField(max_length=50, blank=True, null=True, verbose_name='feed#')
    spider = models.CharField(max_length=50, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='sites', null=True)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='updated_by', null=True)
    note = models.TextField(blank=True, null=True)
    condition = models.BooleanField()
    unit = models.BooleanField()
    year = models.BooleanField()
    make = models.BooleanField()
    model = models.BooleanField()
    trim = models.BooleanField()
    stock_number = models.BooleanField()
    vin = models.BooleanField()
    vehicle_url = models.BooleanField()
    msrp = models.BooleanField()
    price = models.BooleanField()
    selling_price = models.BooleanField()
    rebate = models.BooleanField()
    discount = models.BooleanField()
    images = models.BooleanField()
    images_count = models.BooleanField()
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    date_updated = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return str(self.site_name) or ''

    #  reverse return the full url as a string for creating site view or use  get_success_url(self) at CBV
    def get_absolute_url(self):
        """must follow and return the set url pattern i,e :
        project/<project_name>/<str:pk>/

        reverse(*args,**kwargs) is same as reverse_lazy(*args,**kwargs). Example:
            reverse_lazy('site-detail', kwargs={'project_name': self.project, 'pk': self.pk})
        """
        return reverse('site-detail', kwargs={'project_name': self.project, 'pk': self.pk})

    # def save(self, force_insert=False, force_update=False):
    #     self.entry_code = ''
    #     existing_entry_code = TargetSite.objects.all().order_by('-entry_code')
    #     if existing_entry_code.count() > 0:

    #         new_entry_code = int(existing_entry_code.count()) + 1
    #     else:
    #         new_entry_code = 1
    #     self.entry_code = f'SB-{new_entry_code}'
    #     super().save(force_insert, force_update)


class Scrape(models.Model):
    spider = models.CharField(max_length=50, null=True, blank=True)
    category = models.CharField(max_length=50, null=True, blank=True)
    unit = models.CharField(max_length=200, null=True, blank=True)
    year = models.CharField(max_length=10, null=True, blank=True)
    make = models.CharField(max_length=50, null=True, blank=True)
    model = models.CharField(max_length=200, null=True, blank=True)
    trim = models.CharField(max_length=200, null=True, blank=True)
    stock_number = models.CharField(max_length=50, null=True, blank=True)
    vin = models.CharField(max_length=50, null=True, blank=True)
    vehicle_url = models.CharField(max_length=255, null=True, blank=True)
    msrp = models.CharField(max_length=50, null=True, blank=True)
    price = models.CharField(max_length=50, null=True, blank=True)
    selling_price = models.CharField(max_length=50, null=True, blank=True)
    rebate = models.CharField(max_length=50, null=True, blank=True)
    discount = models.CharField(max_length=50, null=True, blank=True)
    image_urls = models.TextField(null=True, blank=True)
    images_count = models.CharField(max_length=50, null=True, blank=True)
    page = models.CharField(max_length=50, null=True, blank=True)
    last_checked = models.DateTimeField(auto_now_add=True, null=True)
    target_site = models.ForeignKey(TargetSite, on_delete=models.CASCADE, related_name='scrapes', null=True)

    def __str__(self):
        return f'{self.target_site} - stk: {self.stock_number} - {self.last_checked.strftime("%Y-%m-%d %I:%M:%S %p")}'


class SpiderLog(models.Model):
    spider_name = models.CharField(max_length=50, null=True)
    allowed_domain = models.CharField(max_length=50, null=True)
    items_scraped = models.CharField(max_length=50, null=True)
    items_dropped = models.CharField(max_length=50, null=True)
    finish_reason = models.CharField(max_length=50, null=True)
    request_count = models.CharField(max_length=50, null=True)
    status_count_200 = models.CharField(max_length=50, null=True)
    start_timestamp = models.CharField(max_length=50, null=True)
    end_timestamp = models.CharField(max_length=50, null=True)
    elapsed_time = models.CharField(max_length=50, null=True)
    elapsed_time_seconds = models.CharField(max_length=50, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    target_site = models.ForeignKey(TargetSite, on_delete=models.CASCADE, related_name='spider_logs')

    def __str__(self):
        return f'{str(self.target_site)} - {self.items_scraped} | {self.date_created.strftime("%Y-%m-%d %I:%M:%S %p")}'

webscraping/project/api/views.py
from datetime import datetime, timedelta

from rest_framework import status
from rest_framework.authentication import TokenAuthentication
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.throttling import UserRateThrottle

from project.models import Scrape, TargetSite

from .serializers import ScrapeSerializer


@api_view(['GET'])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])
def get_scraped_items(request):

    if 'webproviders' not in request.GET or 'domains' not in request.GET:
        return Response({'detail': 'Bad Request.'}, status=status.HTTP_404_NOT_FOUND)

    providers = 'available' if request.GET.get('webproviders') == 'available' else request.GET.get('webproviders', False).split(',')
    domain = request.GET.get('domains', False)

    # stored returned api data
    web_providers_data = []

    # filtered scrape day
    date_threshold = datetime.now() - timedelta(hours=48)

    if providers == 'available' and domain == 'all':

        all_providers = sorted(list({wb.web_provider for wb in TargetSite.objects.all()}))

        for provider in all_providers:
            scrapes = Scrape.objects.filter(spider__iexact=provider).all()  # last_checked__gte=date_threshold
            domain_names = list({scrape.target_site.site_id for scrape in scrapes})
            sites = []

            if scrapes:
                for name in domain_names:
                    item_data = scrapes.filter(target_site=name).all()

                    serializers = ScrapeSerializer(item_data, many=True)
                    sites.append({name: serializers.data})
                web_providers_data.append({provider: sites})

        return Response(web_providers_data)

    # resolved
    elif len(providers) >= 1 and domain == 'all':
        for provider in sorted(providers):
            scrapes = Scrape.objects.filter(spider__iexact=provider).all()  # last_checked__gte=date_threshold
            domain_names = list({scrape.target_site.site_id for scrape in scrapes})
            sites = []

            if not scrapes:
                return Response({'detail': 'Items not found.'}, status=status.HTTP_404_NOT_FOUND)

            for name in domain_names:
                item_data = scrapes.filter(target_site=name).all()

                serializers = ScrapeSerializer(item_data, many=True)
                sites.append({name: serializers.data})
            web_providers_data.append({provider: sites})

        return Response(web_providers_data)

    elif len(providers) == 1 and domain != 'all':
        scrapes = Scrape.objects.filter(spider__iexact=providers[0], target_site=domain).all()  # last_checked__gte=date_threshold
        sites = []

        if not scrapes:
            return Response({'detail': 'Items not found.'}, status=status.HTTP_404_NOT_FOUND)

        serializers = ScrapeSerializer(scrapes, many=True)
        sites.append({scrapes[0].target_site.site_id: serializers.data})
        web_providers_data.append({providers[0]: sites})
        return Response(web_providers_data)

    else:
        return Response({'detail': 'Bad Request.'}, status=status.HTTP_400_BAD_REQUEST)


# using axios

# const searchWiki = async () => {
#     const reponse = await axios.get('http://localhost:8000/api/scraped-items/aim-dealers/', {
#     method: 'get',
#     params: {
#         webproviders: 'available',
#         domains: 'all',
#     },
#     headers: {
#         Authorization: 'Token f4b2d04a39d6fe6e4a7e04d444924daaefa33497',
#     },
#     });
#     console.log(reponse.data);
# };

webscraping/project/templates/project/targetsite_form.html
{% extends 'project/base.html'%}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% load crispy_forms_tags %}
{% load crispy_forms_utils %}
{% load custom_filters %}


{% block title %}  Scrape Bucket - {{ request.resolver_match.url_name | title}}{% endblock %}  <!--same as "object.site_name" -->
{% block content %} 
<section class="dealer-details">   
    <div class="target-sites-scrape-new pt-3 pb-3">
        <h3 align="left" class="ml-3 pt-3"> {{ request.resolver_match.url_name | str_split:'-' | str_join:' ' | title }}</h3>  
        <form method="POST" enctype="multipart/form-data" novalidate>     
            {% csrf_token %}  
                <fieldset class="form-group mr-4 ml-4" >
                    <legend class=" profile-info"> Information </legend>  
                        <div class="new-scrape-content"> 
                            <div class="new-scrape-inputs col-6"> 
                                <div class="form-input-div">
                                    {{ form.site_name|as_crispy_field }}
                                </div>
                                <div class="form-input-div">
                                    {{ form.site_url|as_crispy_field }}  
                                </div>
                                <div class="form-input-div">
                                    {{ form.web_provider|as_crispy_field }}  
                                </div>
                                <div class="form-input-div">
                                    {{ form.project|as_crispy_field }}
                                </div>                                                                 
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                      <label for="id_site_id">{{form.site_id.label}} <i data-html="true" class="fa fa-question-circle fa-1x red-tooltip" data-placement="top" data-toggle="tooltip" data-original-title="Example: <br> url: <i>https://www.google.com</i> <br> domain_name: <i>google</i>  "></i></label>
                                      {{form.site_id}}
                                      {% if form.errors %}
                                      <strong> {{ form.errors.site_id }}</strong>
                                      {% endif %} 
                                    </div>
                                    <div class="form-group col-md-6">
                                      {{form.feed_id.label_tag}}
                                      {{form.feed_id}}
                                    </div>
                                </div>
                                <div class="form-input-div">
                                    {{ form.status|as_crispy_field }} 
                                </div>                       
                            </div>    
                                <div class="ml-3">                                                            
                                    <div class="new-scrape-legend">
                                        Items to download:
                                    </div>     
                                    <div class="new-scrape-checkboxes">  
                                        <div> 
                                            {{ form.condition|as_crispy_field }}
                                            {{ form.unit|as_crispy_field }}
                                            {{ form.year|as_crispy_field }}
                                            {{ form.make|as_crispy_field }}
                                            {{ form.model|as_crispy_field }}
                                            {{ form.trim|as_crispy_field }}
                                            {{ form.stock_number|as_crispy_field }}   
                                        </div>
                                        <div> 
                                            {{ form.vin|as_crispy_field }}
                                            {{ form.vehicle_url|as_crispy_field }}
                                            {{ form.msrp|as_crispy_field }}
                                            {{ form.price|as_crispy_field }}
                                            {{ form.selling_price|as_crispy_field }}
                                            {{ form.rebate|as_crispy_field }}
                                            {{ form.discount|as_crispy_field }}
                                            
                                        </div>
                                        <div>                                        
                                            {{ form.images|as_crispy_field }}
                                            {{ form.images_count|as_crispy_field }}
                                        </div>                                                                                           
                                    </div>  
                                <div class="check-uncheck__all">                                   
                                    <i class="fa fa-check-square-o check__all" aria-hidden="true" data-placement="top" data-toggle="tooltip" data-original-title="Select all">  </i>
                                    <i class="fa fa-square-o uncheck__all" aria-hidden="true" data-placement="top" data-toggle="tooltip" data-original-title="Unselect all"></i>
                                </div>                                                            
                                <div class=""> 
                                    {{ form.note|as_crispy_field }}
                                </div>                           
                            </div>       
                        </div>                          
                              
                </fieldset>                  
                <div class="form-group btn-group__access" style="justify-content:flex-start">
                 {% with request.resolver_match.url_name as url_name %} 
                   {% if url_name == 'new-scrape'%} 
                         <button class="btn btn-success btn__accessb btn-sm" type="submit" >Submit</button>  
                    {% else %}
                         <button class="btn btn-success btn__access btn-sm "type="submit">Save</button>
                         <a class="btn btn-secondary btn__accessb btn-sm" href="{% url 'site-detail' targetsite.project targetsite.pk%}"> Back </a>  
                   {% endif %}  
                {% endwith %}    
                </div>         
        </form>      
    </div>     
</section>
{% endblock content%}

{% block js %} 
// Add datalist
const status = document.getElementById('div_id_status');
const domain = document.getElementById('id_site_id')

// hide status if new-scrape
if('{{request.resolver_match.url_name}}' === 'new-scrape' || '{{request.user.is_superuser}}' ==='False') status.style.display ='none'
// add input validation indicator
if('{{form.errors.site_id}}') domain.classList.add('is-invalid') 
 
addProviderDataList(
 addAimDealerList,
 '/web-provider-json/',
 '/aim-dealer-provider-json/'
);

 
{% endblock %}   

webscraping/project/templates/project/targetsites.html

{% extends 'project/base.html'%}
{% load static %}
{% block content %} 
{% load tz %}
{% load custom_filters  %}
{% block title %} Scrape Bucket/Project  - {{ project | str_split:'-' | str_join:' ' | title  }} {% endblock %}
    <section class="site-list"> 
        <div  class="target-sites">  
            <h3 align="left" class="ml-3 pt-3"> {{project | str_split:'-' | str_join:' '| title | str_upper:'Aim' | str_upper:'Vdp' | str_upper:'Urls'}}</h3>  
            <center class="dropdown__menus">
                <table>
                    <tbody>
                    <tr>
                        <td align="left" class="status_filter">
                        <span>Status</span> <br />
                        <select class="form-group" id="scrape-status">
                            <option value="">ALL</option>
                            {% with sites|get_field_values:'status' as statuses %}  
                            {% for status in statuses %}
                                <option value="{{ status }}"> {{ status }} </option>
                            {% endfor %} 
                            {% endwith %}                                                    
                        </select>
                        </td>                 
                        <td align="left" class="temp_filter">
                        <span>Web Provider</span> <br />
                        <select id="site-provider">
                            <option value="">ALL</option>
                            {% with sites|get_field_values:'web_provider' as web_providers %}  
                            {% for provider in web_providers %}
                                <option value="{{ provider }}"> {{ provider }} </option>
                            {% endfor %} 
                            {% endwith %}   
                        </select>
                        </td>                  
                    </tr>
                    </tbody>
                </table>
                </center>                     
            <table id="dealers-list-table" class="table  table-hover ">    
                <thead class="thead-light">
                    <tr>
                    <th style="text-align:center" scope="col">Seq#</th>
                    <th>Site Name</th>         
                    <th>Site URL</th>
                    <th>Provider</th>
                    <th >Status</th>                   
                    <th>Last Run</th>                    
                    <th>Owner</th>                   
                    <th>Create Date</th>                   
                    <th style="text-align:center">Actions</th>                   
                    </tr> 
                </thead>
                <tbody id="sites_list" > 
                {% for site in sites %}  
                    <tr>                        
                    <td scope="row" align="center" >                        
                        <div class="darker__primary hover__effect  table-hover"> 
                            <a href=" {% url 'site-detail' site.project site.pk %}" >{{ site.entry_code }}</a>
                        </div>
                    </td>
                    <td>
                        <div class="darker__primary hover__effect">
                            <a href=" {% url 'site-detail' site.project site.pk %}" >{{ site.site_name.dealer_name }} </a>
                        <div>
                    </td>
                    <td>
                        <div class="lighter__primary hover__effect">
                                <a href=" {{ site.site_url }}" target="_blank"> {{ site.site_url }}</a>
                        </div>
                    </td>
                    <td>  
                        <div>                     
                                {{ site.web_provider }}                               
                        </div>                     
                    </td>
                    <td align="left">
                        <div class="status {{site.get_status_display|lower}}">
                            <span>{{ site.get_status_display|upper }}</span>
                        </div>
                    </td>                    
                    <td>
                        <div>
                            {% if site.get_status_display == 'Pending' %}
                            processing...
                            {% elif site.get_status_display == 'Inactive' %}
                            paused
                            {% elif  site.spider_logs.last.date_created|date:'dmY' == site.scrapes.last.last_checked|date:'dmY' %}
                            {{ site.scrapes.last.last_checked | timezone:'US/Eastern'|date:'Y-m-d H:i:s' | replace_if_empty:'running...'}}
                            {% else %}
                            running...
                            {% endif %}
                        </div>
                    </td>
                    <td style="text-align:left" title="created by: {{site.author}}">
                        <div>
                            <span class="author__image"><img src="{{ site.author.profile.image.url }}" aria-label="{{site.author}}"></span> 
                            <span>{{ site.author | title}}</span>
                        </div>
                    </td>   
                    <td style="text-align:left">
                        <div>
                            <span>{{ site.date_created |timezone:'US/Eastern'|date:'Y-m-d'}}</span>                            
                        </div>
                    </td>                  
                    <td align="center"> 
                        <div class="download-delete-btn">                  
                        <a href="{% url 'scrape-csv' sites.first.project.name %}?target_id={{site.pk}}" >
                            <div class="download-btn">
                                <div class="left">
                                    <i class="fas fa-download"></i> 
                                </div>
                                <div class="right">
                                    <i class="fas fa-file-csv"></i>
                                </div>
                            </div>    
                        </a>                                            
                            <div class="delete-btn openDeleteModal" data-site-id="{{site.site_id}}" data-site-name="{{site}}" data-entry-code="{{site.entry_code}}">
                                <div class="left">
                                    <i class="fas fa-times"></i>
                                </div>
                                <div class="right">
                                    <i class="fas fa-trash"></i>                                  
                                </div>
                            </div>          
                        </div>                                        
                    </td>
                    </tr> 
                {% endfor%}           
                </tbody >       
            </table>          
        </div>    
    </section>    
{% endblock content%}
{% block js %} 

    const deleteItemModal = func => func('{{project}}','site-info')

{% endblock %}