webscraping/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views
from .views import SiteCreateView, SiteDeleteView, SiteDetailView, SiteListView, SiteUpdateView

urlpatterns = [
    path('', views.home, name='home'),
    path('project/<project_name>/', SiteListView.as_view(), name='site-list'),
    path('project/<project_name>/<str:pk>/', SiteDetailView.as_view(), name='site-detail'),
    path('scrape/new/', SiteCreateView.as_view(), name='new-scrape'),
    path('project/<project_name>/<str:pk>/update', SiteUpdateView.as_view(), name='update-scrape'),
    path('project/<project_name>/<site>/<str:pk>/delete', SiteDeleteView.as_view(), name='delete-scrape'),
    path('api-docs/', views.api_docs, name='api-docs'),
    path('help/', views.help, name='help'),
    path('scrape-data-json/', views.scrape_data_json, name='scrape-json'),
    path('spider-log-json/', views.spider_logs_json, name='log-json'),
    path('web-provider-json/', views.web_providers_json, name='log-json'),
    path('aim-dealer-provider-json/', views.aim_dealers_list, name='aim-dealer-json'),
    path('project/<project_name>/export_scrape_by_csv', views.scrape_data_csv, name='scrape-csv'),
    # path('api/scraped-items/', views.test_api, name='test'),
]


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webscraping/webscraping/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_view
from django.urls import include, path
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', user_views.MyLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path(
        'password-reset/',
        auth_view.PasswordResetView.as_view(
            template_name='users/password_reset.html'),
        name='password_reset'),
    path(
        'password-reset/done/',
        auth_view.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm',
    ),
    path(
        'password-reset-complete/',
        auth_view.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete',
    ),
    path('', include('project.urls')),
    # rest framework urls
    path('api/scraped-items/aim-dealers/', include('project.api.urls', 'api-scrape')),  # namespace of 'api-scrape'
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webscraping/users/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image

from users.utils import image_resize


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default_img.png', upload_to='profile_pics')
    # Note: default image must available at media dir, i.e: MEDIA_URL = '/images/'

    def __str__(self):
        return f'{self.user.username} profile'

    # Overide the save method in the backend
    def save(self, *args, **kwargs):
        # run the save method from the parent class and save the image no matter how large the image size is
        image_resize(self.image, 280, 280)
        super().save(*args, **kwargs)

    # Other option:
    # img = Image.open(self.image.path)

    # if img.height > 300 or img.width > 300:
    #     output_size = (300, 300)
    #     img.thumbnail(output_size)
    #     img.save(self.image.path)


# ! NOTES:
# Profile Model for image needs the PILLOW package in the backend
# The save(self) is the method that get runs after our Model is saved. It's a method that already exists in the parent Class, but we're creating our own so we can add some functionalities

webscraping/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _  # customize log-in views

from .models import Profile


# Register form
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {
            'username': 'None',
        }


# For custom login views use
class MyLogInForm(AuthenticationForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'style': 'margin:1rem 0 2rem', 'placeholder': 'Username'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'mb-4', 'placeholder': 'Password'}))

    error_messages = {
        'invalid_login': _("Invalid login. Note that both " "fields may be case-sensitive."),
        'inactive': _("This account is inactive."),
    }


# User update form
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(label='Email')

    class Meta:
        model = User
        fields = ['username', 'email']
        help_texts = {
            'username': None,
        }


# Update profile image
class ProfileUpdateForm(forms.ModelForm):
    image = forms.ImageField(label='', widget=forms.FileInput)
    image.widget.attrs['style'] = 'visibility: hidden'

    class Meta:
        model = Profile
        fields = ['image']
        # widgets = {
        #     'image': forms.FileInput(),
        # }

webscraping/users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render

from .forms import MyLogInForm, ProfileUpdateForm, UserRegisterForm, UserUpdateForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f' Your account has been created! Your now able to log in', extra_tags='text-center')
            return redirect('login')
    else:

        form = UserRegisterForm()

    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):

    # populate form input values
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        # restrict to edit 'test user' profile
        if str(request.user) == 'testuser':
            messages.warning(request, f'You are not authorized to edit this profile. ', extra_tags='exclamation')
            return redirect('profile')

        # if Valid form entries, update form(username, email or image profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            if request.user.is_authenticated:
                messages.success(request, f' Your account has been updated', extra_tags='check')
            return redirect('profile')  # prevent the browser's msg of resubmitting when reloading, i.e, 'POST-GET redirect pattern'

    else:
        # instantiate UserUpdateForm & ProfileUpdateForm class and sent value to template
        user_form = UserUpdateForm(instance=request.user)  # "instance=request.user" will populate the username and email in profile form
        profile_form = ProfileUpdateForm(instance=request.user.profile)  # "instance=request.user.profile" will populate the images profile form

    context = {
        'dropdown_arrow': 'down',
        'user_form': user_form,
        'profile_form': profile_form,
    }

    return render(request, 'users/profile.html', context)


class MyLoginView(LoginView):
    authentication_form = MyLogInForm

webscraping/users/templates/users/base_user.html

{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title</title>
    <link   rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/register_login.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
   
    {% block content %} {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
      <script type="text/javascript" src="{% static 'js/register_login.js' %}">       
    </script>   
  </body>
</html>

webscraping/users/templates/users/login.html
{% extends "users/base_user.html" %}
{% load static%}
{% load crispy_forms_tags %}
{% block content %}
    <div class="login-container "> 
        <div class="error-msg-box ">           
            {% if  form.errors %}
                <div class="alert alert-danger text-center error-msg">
                 <i class="fas fa-exclamation-circle" ></i> 
                 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>                   
                    {% for _, error in form.errors.items %}
                           <div> {{ error|striptags }}</div>
                    {% endfor %}  
              </div>    
            {% endif %}                        
         </div>  

      <div class="success-msg-box ">  
         {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.level_tag }} sign__up {{ message.extra_tags }}">
                <i class="fas fa-check-circle" ></i> 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>                      
                    {{ message }}                    
              </div>              
            {% endfor %}
          {% endif %}
        </div>
           <!-- content block -->
         
      <div class="login-content ">
        <form  method="POST" class="form-group">
            {% csrf_token %}
          <img src="{% static 'images/profile_login.png' %}"  class="slide-in-fwd-center"/>
          <h2 class="title">Log in to Scrape Bucket</h2>
          <div class="input-div one">
            <div class="i">
              <i class="fas fa-user"></i>
            </div>
            <div class="div">
              <h5>{{ form.username.label }}</h5>
              <input type="text" class="input" name="username" required/>
            </div>
          </div>
          <div class="input-div pass">
            <div class="i">
              <i class="fas fa-lock"></i>
            </div>
            <div class="div">
              <h5>{{ form.password.label }}</h5>
               <input type="password" class="input password-input" name="password" required />
               <span class= "eyes">
                 <i class="fas fa-eye"></i>
                 <i class="fas fa-eye-slash"></i>
               </span>
            </div>
          </div>
          <a href="{% url 'password_reset' %}" class="password-reset" >Forgot Password?</a>
          <input type="submit" class="btn" value="Sign In" />  
          
          <div class="border-top sign-up">
            <small class="text-muted">
              Don't have an account? <a href="{% url 'register' %}" class="">Sign Up</a>
            </small>
        </div>
        </form>        
      </div>
    </div>
    
   {% endblock content %}
    

webscraping/users/templates/users/logout.html
{% extends "users/base_user.html" %} 
{% block content %}  
  <div class="container text-center mt-4">
    <h2> You've been logged out</h2>      
        <div class="border-top pt-3">
            <small class="" style="font-weight:500">
                <a href="{% url 'login' %}" class="">Log In Again</a> 
            </small>
        </div>  
    </div>
{% endblock content %}

webscraping/users/templates/users/password_reset.html
{% extends "users/base_user.html" %}
{% load static%}
{% load crispy_forms_tags %}
{% block content %}
    <div class="login-container "> 
        <div class="error-msg-box ">           
            {% if  form.errors %}
                <div class="alert alert-danger text-center error-msg">
                 <i class="fas fa-exclamation-circle" ></i> 
                 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>                   
                    {% for _, error in form.errors.items %}
                           <div> {{ error|striptags }}</div>
                    {% endfor %}  
              </div>    
            {% endif %}                        
         </div>  

      <div class="success-msg-box ">  
         {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.level_tag }} sign__up {{ message.extra_tags }}">
                <i class="fas fa-check-circle" ></i> 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>                      
                    {{ message }}                    
              </div>              
            {% endfor %}
          {% endif %}
        </div>
           <!-- content block -->
         
      <div class="login-content ">
        <form  method="POST" class="form-group">
            {% csrf_token %}
          <img src="{% static 'images/profile_login.png' %}"  class="slide-in-fwd-center"/>
          <h2 class="title">Reset Your Password</h2>
          <div class="input-div one">
            <div class="i">
              <i class="fas fa-envelope"></i>
            </div>
            <div class="div">
              <h5>{{ form.email.label }}</h5>             
              <input type="text" class="input" name="email" required/>
            </div>
          </div>                 
          <input type="submit" class="btn" value="Password Reset" />          
          <div class="border-top sign-up">
            <small class="text-muted">
              Back to <a href="{% url 'login' %}" class="">Login</a>              
            </small>
          </div>         
        </form>        
      </div>
    </div>
    
   {% endblock content %}

webscraping/users/templates/users/password_reset_complete.html
{% extends "users/base_user.html" %} 
{% block content %}  
    <div class="text-center mt-4 password-reset-done" style="transform:translate(35%,10px)">       
        <div class="success-msg-box ">  
            <div class="alert alert-success sign__up ">
                <i class="fas fa-check-circle" ></i> 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>                      
                Your new  password has been set! 
                <br><br>
                <a href="{% url 'login' %}">Sign in here</a>                  
            </div>
        </div>  
    </div>
{% endblock content %}

webscraping/users/templates/users/password_reset_confirm.html
{% extends "users/base_user.html" %}
{% load static%}
{% load crispy_forms_tags %}
{% block content %}
    <div class="login-container "> 
        <div class="error-msg-box ">           
            {% if  form.errors %}
                <div class="alert alert-danger text-center error-msg">
                 <i class="fas fa-exclamation-circle" ></i> 
                 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>                   
                    {% for _, error in form.errors.items %}
                           <div> {{ error|striptags }}</div>
                    {% endfor %}  
              </div>    
            {% endif %}                        
         </div>  

      <div class="success-msg-box ">  
         {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.level_tag }} sign__up {{ message.extra_tags }}">
                <i class="fas fa-check-circle" ></i> 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>                      
                    {{ message }}                    
              </div>              
            {% endfor %}
          {% endif %}
        </div>
           <!-- content block -->
         
      <div class="login-content ">
        <form  method="POST" class="form-group">
            {% csrf_token %}
          <img src="{% static 'images/profile_login.png' %}"  class="slide-in-fwd-center"/>
          <h2 class="title">Password Reset</h2>
          <div class="input-div pass">           
            <div class="i">                 
              <i class="fas fa-lock"></i>
            </div>
            <div class="div">                
              <h5>{{ form.new_password1.label }}</h5>               
              <input type="password" class="input input-password" name="new_password1" required />                          
            </div>
          </div>
          <div class="input-div pass">
            <div class="i">
              <i class="fas fa-lock"></i>
            </div>
            <div class="div">
              <h5>{{ form.new_password2.label }}</h5>
              <input type="password" class="input input-password"  name="new_password2" required />              
            </div>
          </div> 
          <div class= "text-password">
            <input type="checkbox" id="show-pass" name="show-pass" >
            <label for="show-pass" ><small>Show password</small></label>
          </div>              
          <input type="submit" class="btn" value="Reset" />
        </form>        
      </div>
    </div>
    
   {% endblock content %}

webscraping/users/templates/users/password_reset_done.html
{% extends "users/base_user.html" %} 
{% block content %}  
    <div class="text-center mt-4 password-reset-done" style="transform:translate(35%,10px)">       
        <div class="success-msg-box ">  
            <div class="alert alert-success sign__up ">
                <i class="fas fa-check-circle" ></i> 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>                      
                An Email has been sent with instructions to reset your password                    
            </div>  
        </div>  
    </div>
{% endblock content %}

webscraping/users/templates/users/profile.html
{% extends "project/base.html"  %} 
{% load crispy_forms_tags %}
{% block content %}  
    <div class="profile-wrapper">
        <div class="profile-cover">            
        </div>
        <div class="profile-content-section display-image">
            <form method="POST" enctype="multipart/form-data">     
                {% csrf_token %}       
                <div id="display-image">                
                    <img class="account-img" src="{{ user.profile.image.url }}" id="preview-image">
                    <div class="image-icon-wrapper">
                        <span class="image-icon" for="id_image"> <label for="id_image" class="fas fa-camera"></label> </span>
                        {{ profile_form.image }}
                    </div>  
                    <div class="media-body">                        
                        <h3 class="account-heading">{{ user.username|title }}</h3>
                        <p class="text-secondary">{{ user.email }}</p>
                    </div>
                </div>
                 <div class="profile mr-4 ml-4">
                        <fieldset >
                            <legend class=" profile-info">Profile Info</legend> 
                            <div class="form-group profile-content" >
                                <div class="form-group profile col-md-5">
                                    <label for="exampleInputEmail1">Username</label>
                                    <input type="text" class="form-control form-control-sm text-muted" name="username" id="id_username" value="{{ user.username }}" required>
                                </div>
                                <div class="form-group  profile col-md-5">
                                    <label for="exampleInputPassword1">Email</label>
                                    <input type="email" class="form-control  form-control-sm text-muted" name="email" id="id_email" value="{{ user.email }}" required>  
                                </div>   
                            </div>                 
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-success btn-sm" type="submit">Update</button>
                        </div>
                 </div>
            </form>
        </div>
    </div> 

    <script>
        const inputImage = document.querySelector('#id_image');
        const displayImage = document.querySelector('#display-image');
        const previewImage = displayImage.querySelector('#preview-image');
       
        inputImage.addEventListener('change', function() {
            const file = this.files[0];           
            if (file) {
                const reader = new FileReader();               
                reader.addEventListener('load', function(){                    
                   previewImage.setAttribute('src', this.result)
                })
                reader.readAsDataURL(file)
            }           
        })
        
        
    </script>
{% endblock content %}

webscraping/users/templates/users/register.html

{% extends "users/base_user.html" %}
{% load static %}
{% block content %}
<!-- Custom Error Message -->   
    <div class="register-container">   
        <div class="error-msg-box ">           
            {% if  form.errors %}
                <div class="alert alert-danger text-center error-msg">
                 <i class="fas fa-exclamation-circle" ></i> 
                 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>                   
                    <div class="messages"> {{ form.username.errors|striptags }}</div>
                    <div class="messages"> {{ form.email.errors |striptags }}</div>
                    <div class="messages"> {{ form.password2.errors |striptags }}</div>
                    <!-- {% for _, error in form.errors.items %}
                           <div class="error-messages"> {{ error|striptags }}</div>
                         {% endfor %}  -->
              </div>    
            {% endif %}
                        
         </div>  
      <div class="login-content">
        <form method="POST" class="form-group">
         {% csrf_token %}  
          <img src=" {% static 'images/resume.png' %}" />
          <h2 class="title">Create your Account</h2>
          <div class="input-div one">
            <div class="i">
              <i class="fas fa-user"></i>
            </div>
            <div class="div">
              <h5>{{ form.username.label }}</h5>
              <input type="text" class="input" name="username" required />             
            </div>
          </div>
          <div class="input-div one">
            <div class="i">
              <i class="fas fa-envelope"></i>
            </div>
            <div class="div">
              <h5>{{ form.email.label }}</h5>
              <input type="text" class="input" name="email" required />
            </div>
          </div>
          <div class="input-div pass">           
            <div class="i">                 
              <i class="fas fa-lock"></i>
            </div>
            <div class="div">                
              <h5>{{ form.password1.label }}</h5>               
              <input type="password" class="input input-password" name="password1" required />                          
            </div>
          </div>
          <div class="input-div pass">
            <div class="i">
              <i class="fas fa-lock"></i>
            </div>
            <div class="div">
              <h5>{{ form.password2.label }}</h5>
              <input type="password" class="input input-password"  name="password2" required />              
            </div>
          </div>  
          <div class= "text-password">
            <input type="checkbox" id="show-pass" name="show-pass" >
            <label for="show-pass" ><small>Show password</small></label>
          </div>                
          <input type="submit" class="btn" value="Sign Up" />            
          <div class="border-top sign-up">
            <small class="text-muted">
              Already have an account? <a href="{% url 'login' %}" class="">Sign In</a>
            </small>
          </div>
           
        </form>        
      </div>
    </div>  
{% endblock content %}
   